// Numbers shown on the landing page come from docs/status.md, which is
// generated by `tools/project-status.sh --check`. Keep them in one object so
// a stale badge is a one-line edit, and the CI gate is the source of truth.
export const stats = {
  rustTests: 353,
  workspaceCrates: 5,
  nativeBindings: 90,
  specialForms: 24,
  cards: [
    { value: 353, label: 'Rust 自动化单元测试 (100% Passing)' },
    { value: 90, label: 'Native Bindings (含 WASM / JS FFI)' },
    { value: 24, label: 'Special Forms 特殊形式' },
    { value: 5, label: 'Workspace Crates (core + cli + ai + grove + grove-app)' },
  ],
};
